/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * The crown-button element.
     */
    interface CrownButton {
        /**
          * The color of the button.
         */
        "color": string;
        /**
          * Indicates whether the button is disabled.
         */
        "disabled": boolean;
        /**
          * The URL if the button behaves as a link.
         */
        "href": string;
        /**
          * The size of the button (e.g., small, medium, large).
         */
        "size": string;
        /**
          * The target window or frame if the button behaves as a link.
         */
        "target": string;
        /**
          * The type of the button (e.g., submit, reset, button).
         */
        "type": string;
        "useShadowDOM": boolean;
        /**
          * The variant of the button (e.g., outlined, contained, text).
         */
        "variant": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    /**
     * The crown-button element.
     */
    interface HTMLCrownButtonElement extends Components.CrownButton, HTMLStencilElement {
    }
    var HTMLCrownButtonElement: {
        prototype: HTMLCrownButtonElement;
        new (): HTMLCrownButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "crown-button": HTMLCrownButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * The crown-button element.
     */
    interface CrownButton {
        /**
          * The color of the button.
         */
        "color"?: string;
        /**
          * Indicates whether the button is disabled.
         */
        "disabled"?: boolean;
        /**
          * The URL if the button behaves as a link.
         */
        "href"?: string;
        /**
          * The size of the button (e.g., small, medium, large).
         */
        "size"?: string;
        /**
          * The target window or frame if the button behaves as a link.
         */
        "target"?: string;
        /**
          * The type of the button (e.g., submit, reset, button).
         */
        "type"?: string;
        "useShadowDOM"?: boolean;
        /**
          * The variant of the button (e.g., outlined, contained, text).
         */
        "variant"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "crown-button": CrownButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The crown-button element.
             */
            "crown-button": LocalJSX.CrownButton & JSXBase.HTMLAttributes<HTMLCrownButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
